quimerahg/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    # Apps
    url(r'^', include('portal.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^tinymce/', include('tinymce.urls')),
    # Media y static
    (r'^media/(?P<path>.*)$','django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT,'show_indexes': True}),
    (r'^static/(?P<path>.*)$','django.views.static.serve',
         {'document_root': settings.STATIC_ROOT,'show_indexes': True}),
)

share/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

# Reescribir esta url con los parámetros adecuados para el template y la ruta
# si se desea cambiar el formato del correo en html enviado.
urlpatterns = patterns('share.views',
    url(r'^send/$',
        'send_share',
        {"template": "default_share_email.html",
         "path": ""},
        name='send_share'),
)

adminphotoload/models.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, patterns
from django.contrib import admin
from django.db.models.loading import get_model
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from common.forms import AdminFotoForm, AdminDeleteFotoForm
from common.models import *
from common.utils import json_response, direct_response


class PhotoFrameAdmin(admin.ModelAdmin):
    """
    Modelo para subir fotos usando el widget en un iframe mediante ajax
    """
    exclude = ('fotos',)

    def get_urls(self):
        """
        URLs para subir fotos y borrarlas
        """
        urls = super(PhotoFrameAdmin, self).get_urls()
        my_urls = patterns('',
            url('^add_fotos/(?P<app>[\w]+)/(?P<model>[\w]+)/(?P<id>\d+)?$',
                self.admin_site.admin_view(self.add_fotos),
                name='admin_add_fotos'),
            url('^ajax_edit_foto/$',
                self.admin_site.admin_view(self.ajax_edit_foto),
                name='admin_ajax_edit_foto'))

        return my_urls + urls

    def add_fotos(self, request, app, model, id):
        """
        página que muestra la herramienta para subir y editar fotos
        """
        Model = get_model(app, model)
        obj = get_object_or_404(Model, id=id)
        form_add = AdminFotoForm()
        form_del = AdminDeleteFotoForm()
        if request.method == 'POST':
            if 'delete' not in request.POST:
                form_add = AdminFotoForm(request.POST, request.FILES)
                if form_add.is_valid():
                    form_add.saveTo(obj)
                    form_add = AdminFotoForm()
                    form_add.success = True
            else:
                form_del = AdminDeleteFotoForm(request.POST)
                if form_del.is_valid():
                    form_del.save()
                    form_del = AdminDeleteFotoForm()
                    form_del.success = True
        fotos = obj.fotos.all()

        return direct_response(request, 'add_photos.html', {'form_add': form_add,
                                                            'form_del': form_del,
                                                            'fotos': fotos})

    @csrf_exempt
    def ajax_edit_foto(self, request):
        """
        si el id recibido es correcto devuelve el nombre y descripcion de la
        foto
        """
        if request.method == 'POST':
            try:
                foto = Foto.objects.get(id=request.POST['id'])
                data = foto.__dict__
                data.pop('imagen')
                data.pop('_state')
            except Foto.DoesNotExist:
                data = {'response': 'el id no pertenece a ninguna foto'}

            return json_response(data)

common/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.shortcuts import get_object_or_404
from common.models import Foto


class AdminFotoForm(forms.ModelForm):
    """
    Formulario para guardar las fotos
    """
    id = forms.IntegerField(widget=forms.HiddenInput, required=False)
    imagen = forms.ImageField(required=False)

    class Meta:
        model = Foto

    def clean(self):
        """
        Verifica que la im\xc3\xa1gen principal pueda estar ausente sólo si
        existe id
        """
        cleaned_data = super(self.__class__, self).clean()
        id = cleaned_data.get('id')
        imagen = cleaned_data.get('imagen')
        if not imagen and not id:
            self._errors['imagen'] = \
                self.error_class([u'Este campo es obligatorio'])

        return cleaned_data

    def saveTo(self, obj):
        """
        Graba(o actualiza) la foto y la agrega a los objectos relacionados
        del objeto p, siempre y cuando el related name sea fotos
        """
        id = self.cleaned_data.get('id')
        new_img = self.cleaned_data.get('imagen')
        if not new_img:
            new_img = Foto.objects.get(id=id).imagen
        foto = Foto(id=id, nombre=self.cleaned_data.get('nombre'),
                    imagen=new_img)
        foto.save()
        if not id:
            obj.fotos.add(foto)

        return foto


class AdminDeleteFotoForm(forms.Form):
    """
    Formulario para borrar las fotos
    """
    id = forms.IntegerField(widget=forms.HiddenInput)

    def save(self):
        """
        borra la foto
        """
        foto = get_object_or_404(Foto, id=self.cleaned_data['id'])

        return foto.delete()

adminphotoload/templates/add_photos.html
{% extends "admin/base.html" %}

{% load i18n thumbnail %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}admin/css/forms.css"/>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}adminphotoload/css/widgets.css"/>
{% endblock %}

{% block extrahead %}
    <script src="http://code.jquery.com/jquery-1.8.3.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            var fotos_length = '{{ fotos|length }}';
            $("img[pos='0']").removeClass('no-display').addClass('selected');
            $('form#deleteForm input#id_id').attr('value', $('img[pos="0"]').attr('id'));
            $('form#editForm input#id_id').attr('value', $('img[pos="0"]').attr('id'));

            $.fn.nextFoto = function(){
                //si no existe ninguna foto retorna 0
                //si existe una sgte foto la muestra sino regresa a la primera
                //actualiza el valor id del form para borrar y editar
                if ($('img[pos="0"]').length == 0){
                    return 0;
                }
                var Alt = $(this).attr('pos');
                $(this).attr('class','no-display');
                Alt++;
                var next = $('img[pos='+Alt+']');
                if (next.length > 0){
                    var imgAlt = $('img[pos='+Alt+']')
                }else{
                    var imgAlt = $('img[pos="0"]')
                }
                imgAlt.attr('class', 'selected');
                $('form#deleteForm input#id_id').attr('value',imgAlt.attr('id'));
                $('form#editForm input#id_id').attr('value',imgAlt.attr('id'));
            };

            $.fn.prevFoto = function(){
                //si no existe ninguna foto retorna 0
                //si existe una foto anterior la muestra sino regresa a la última
                //actualiza el valor id del form para borrar
                if ($('img[pos="0"]').length == 0){
                    return 0;
                }
                var Alt = $(this).attr('pos');
                $(this).attr('class','no-display');
                Alt--;
                var next = $('img[pos='+Alt+']');
                if (next.length == 0){
                    var imgAlt = $('img[pos=' + (fotos_length - 1) + ']');
                }else{
                    var imgAlt = $('img[pos=' + Alt + ']');
                }
                imgAlt.attr('class', 'selected');
                $('form#deleteForm input#id_id').attr('value',imgAlt.attr('id'));
                $('form#editForm input#id_id').attr('value',imgAlt.attr('id'));
            };

            $('div.fotosTool_right a').click(function(event){
                event.preventDefault();
                $('img.selected').slideUp(400, function() {
                    $('img.selected').nextFoto();
                });
            });

            $('div.fotosTool_left a').click(function(event){
                event.preventDefault();
                $('img.selected').slideUp(400, function(){
                    $('img.selected').prevFoto();
                });
            });

            $('input[name=edit]').click(function(event){
                event.preventDefault();
                var data = { id: $('form#editForm input#id_id').attr('value') };
                var request = $.ajax({
                    url: "{% url admin:admin_ajax_edit_foto %}",
                    type: "POST",
                    data: data, dataType: "json"
                });
                request.done(function(res, status) {
                    $('input#id_nombre_en').attr('value', res['nombre_en']);
                    $('input#id_nombre_es').attr('value', res['nombre_es']);
                    $('form#fotoForm input#id_id').attr('value', res['id']);
                });
            });
        });
    </script>
{% endblock %}

{% block bodyclass %}change-form{% endblock %}

{% block userlinks %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
    <div id="content-main">
        {% if add_success %}
            <ul class="messagelist">
                <li class="info">La foto fue guardada con éxito</li>
            </ul>
        {% endif %}
        {% if del_success %}
            <ul class="messagelist">
                <li class="info">La foto fue eliminada</li>
            </ul>
        {% endif %}
        {% block form_top %} <h1>{% trans 'Add' %} Foto</h1>{% endblock %}
        <fieldset class='module aligned'>
            <div class='proyecto-form-col1'>
                <!-- Begin Add Foto Form -->
                <form id='fotoForm' enctype='multipart/form-data' action="" method="post">{% csrf_token %}
                    {{ form_add.non_field_errors }}
                    {% for field in form_add %}
                        <div class='form-row'>
                            {{ field.errors }}
                            {% if not field.is_hidden  %}
                                {{ field.label_tag }}
                            {% endif %}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <div class="submit-row" id='addReferencia'>
                        <input id="addReferencia" class="default" type="submit" name="_save" value="{% trans 'Save' %}">
                    </div>
                </form>
                <!-- End Add Foto Form -->
            </div>
            <div class='proyecto-form-col2'>
                <!-- Begin fotos tool -->
                <div class='fotos_tool'>
                    <div class="fotosTool_left">
                        <a href="#"><img src="{{ STATIC_URL }}adminphotoload/img/selector-prev.gif" alt="anterior"></a>
                    </div>
                    <div class="fotosTool_center">
                        <div class="fotosTool_centerRuler">
                        </div>
                        {% for foto in fotos %}
                            <img class="no-display" id="{{ foto.id }}" src="{% thumbnail foto.imagen 200x200 %}" pos="{{ forloop.counter0 }}" title="{{ foto.nombre }}" />
                        {% endfor %}
                    </div>
                    <div class="fotosTool_right">
                        <a href="#"><img src="{{ STATIC_URL }}adminphotoload/img/selector-next.gif" alt="siguiente"/></a>
                    </div>
                    {% if fotos %}
                        <div class='fotosTool_iconDelete'>
                            <form id='deleteForm' action='' method='post'>{% csrf_token %}
                                {{ form_del.id }}
                                <input type='submit' value='{% trans 'Delete' %}' name="delete">
                            </form>
                            <!-- <a class='deletelink' href="#">{% trans 'Delete' %}</a> -->
                        </div>
                        <div class='fotosTool_iconEdit'>
                            <!-- <a class='changelink' href="#">{% trans 'Edit' %}</a> -->
                            <form id='editForm' action='' method='post'>{% csrf_token %}
                                <input id='id_id' type='hidden' name='id'>
                                <input type='submit' value='{% trans 'Edit' %}' name='edit'>
                            </form>
                        </div>
                    {% endif %}
                </div>
                <!-- End fotos tool -->
            </div>
        </fieldset>
    </div>
{% endblock %}