quimerahg/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    # Apps
    url(r'^', include('portal.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^tinymce/', include('tinymce.urls')),
    # Media y static
    (r'^media/(?P<path>.*)$','django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT,'show_indexes': True}),
    (r'^static/(?P<path>.*)$','django.views.static.serve',
         {'document_root': settings.STATIC_ROOT,'show_indexes': True}),
)

share/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

# Reescribir esta url con los parámetros adecuados para el template y la ruta
# si se desea cambiar el formato del correo en html enviado.
urlpatterns = patterns('share.views',
    url(r'^send/$',
        'send_share',
        {"template": "default_share_email.html",
         "path": ""},
        name='send_share'),
)

share/models.py
# -*- coding: utf-8 -*-

from django.contrib.sites.models import Site
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.template import Context, loader
from django.conf import settings


class ShareableClass(models.Model):
    """
    Clase abstracta que genera el botón compartir, se necesita definir un
    objeto Site en la aplicación y sobreescribir el método get_absolute_url de
    la clase que herede de esta o en su defecto el método get_share_url siguiendo
    las especificaciones
    """
    facebook_account = models.CharField(max_length=200,
        verbose_name=_(u"Cuenta de facebook"), blank=True, null=True)
    twitter_account = models.CharField(max_length=200,
        verbose_name=_(u"Cuenta de twitter"), blank=True, null=True)
    google_account = models.CharField(max_length=200,
        verbose_name=_(u"Cuenta de google"), blank=True, null=True)

    class Meta:
        abstract = True

    def get_absolute_url(self):
        """
        Sobreescribir si el modelo tiene una url dentro del dominio
        """
        return False

    def get_share_url(self):
        """
        Sobreescribir si la clase tiene una url en un dominio externo
        """
        pass

    def get_share_button(self):
        """
        Obtiene el código para el botón de compartir
        """
        t = loader.get_template('share_button.html')
        c = Context({'object': self,
                     'domain': Site.objects.get_current().domain,
                     'STATIC_URL': settings.STATIC_URL})

        return t.render(c)


class SimpleShareableClass(models.Model):
    """
    Clase abstracta que genera el botón compartir, se necesita definir un
    objeto Site en la aplicación y sobreescribir el método get_absolute_url de
    la clase que herede de esta o en su defecto el método get_share_url siguiendo
    las especificaciones
    A diferencia de ShareableClass esta no necesita definir cuentas, se puede usar
    en un modelo existente sin necesidad de alterar la base de datos
    """
    class Meta:
        abstract = True

    def get_absolute_url(self):
        """
        Sobreescribir si el modelo tiene una url dentro del dominio
        """
        return False

    def get_share_url(self):
        """
        Sobreescribir si la clase tiene una url en un dominio externo
        """
        pass

    def get_share_button(self):
        """
        Obtiene el código para el botón de compartir
        """
        t = loader.get_template('simple_share_button.html')
        c = Context({'object': self,
                     'domain': Site.objects.get_current().domain,
                     'STATIC_URL': settings.STATIC_URL})

        return t.render(c)

share/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.sites.models import Site
from django.core.validators import email_re
from django.utils.translation import ugettext_lazy as _
from common.utils import send_mass_html_mails
from common.validators import validate_name


class ShareForm(forms.Form):
    """
    Formulario para compartir un objeto por email
    """
    name = forms.CharField(validators=[validate_name])
    emails = forms.CharField(required=False,
        label="e-mails",
        widget=forms.Textarea(attrs={'rows':2}),
        help_text=_(u"e-mails should be separated by commas"))
    message = forms.CharField(required=False,
        widget=forms.Textarea(attrs={'rows':5}))
    url = forms.CharField(widget=forms.HiddenInput)

    def __init__(self, template, path, *args, **kwargs):
        """
        Recibe el path y el nombre del template
        """
        self.template = template
        self.path = path
        super(ShareForm, self).__init__(*args, **kwargs)

    def clean_emails(self):
        """
        Los emails deben tener el formato correcto y estar separados por comas
        """
        if self.cleaned_data["emails"]:
            self.emails = [email.strip() for email in
                           self.cleaned_data["emails"].split(",")]
            for email in self.emails:
                if not email_re.match(email.strip()):
                    raise forms.ValidationError(_(u"There are some invalid e-mail"))

            return self.emails
        else:
            raise forms.ValidationError(_(u"You must enter a e-mail address at "
                                          u"least."))

    def share(self):
        """
        Envía la url y el mensaje a los emails ingresados en el formularios
        """
        send_mass_html_mails(
            u"info@qlabs.com",
            u"%s quiere compartir esta página contigo" % self.cleaned_data["name"],
            self.template,
            {"name": self.cleaned_data["name"],
             "message": self.cleaned_data["message"],
             "url": self.cleaned_data["url"],
             'domain': Site.objects.get_current().name},
            self.emails,
            path=self.path
        )

share/views.py
# -*- coding: utf-8 -*-

from django.views.decorators.csrf import csrf_exempt
from common.utils import direct_response
from share.forms import ShareForm


@csrf_exempt
def send_share(request, template, path):
    """
    Maneja el formulario de envío de correos
    """
    if request.method == "POST":
        form = ShareForm(template, path, request.POST)
        if form.is_valid():
            form.share()
    else:
        form = ShareForm(template, path)

    return direct_response(request, "send_form.html",
                           {"form": form})

share/templates/default_share_email.html
<html>
    <head>
    </head>
    <body>
        <h1>{{ name }} is sharing Quimera Labs with you</h1>
        <p>{{ name }} propose that you visit the <a href="{{ url }}">Quimera Labs' page</a> and send you this message:</p>
        <p>{{ message }}</p>
    </body>
</html>

share/templates/send_form.html
{% load i18n %}

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}portal/css/base.css" />
        <script src="{{ STATIC_URL }}common/js/jquery-1.7.2.min.js" type="text/javascript"></script>

        <script type="text/javascript">
            $(document).ready(function() {
                $("#id_url").val(parent.url);
                {% if form.is_bound and not form.is_valid %}
                    parent.document.getElementById('mail-iframe').height = document['body'].offsetHeight;
                {% endif %}
            })
        </script>

        <style type="text/css">
            .helptext {
                font-size: 11px;
            }
            .errorlist {
                font-size: 11px;
            }
            input[type=text], textarea {
                width: 197px;
            }
            .submit {
                text-align: right;
            }
        </style>
    </head>
    <body>
    {% if form.is_valid %}
        <label>{% blocktrans %}El correo ha sido enviado.{% endblocktrans %}</label>
    {% else %}
        <form action="" method="post">
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td class="right submit">
                        <input type="submit" class="button" value="{% blocktrans %}Enviar{% endblocktrans %}" />
                    </td>
                </tr>
            </table>
        </form>
    {% endif %}
    </body>
</html>

share/templates/share_button.html
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}common/js/jquery.jqpopin/jquery.jqpopin.css" />
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}share/css/share.css" />

<script type="text/javascript" src="{{ STATIC_URL }}common/js/jquery.jqpopin/jquey.jqpopin.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}share/js/share.js"></script>

<script type="text/javascript">
    var url = "http://{{ domain }}{{ object.get_absolute_url }}";
</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=360681610629614";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="share">
    <span class="button">Share</span>
    <table>
        <tbody>
            {# Facebook #}
            <tr>
                {# Share #}
                <td>
                    <a class="fb_share_button" href="http://www.facebook.com/sharer.php?u={% if object.get_absolute_url %}http%3A%2F%2F{{ domain }}{{ object.get_absolute_url }}{% else %}{{ object.get_share_url }}{% endif %}&amp;t={{ object }}" target="_blank">
                        Share
                    </a>
                </td>
                {# Like #}
                <td>
                {% if object.facebook_account %}
                    <iframe src="//www.facebook.com/plugins/like.php?href={{ object.facebook_account }}&amp;send=false&amp;layout=button_count&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=arial&amp;height=21&amp;appId=360681610629614" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:75px; height:21px;" allowTransparency="true"></iframe>
                {% else %}
                    <iframe src="//www.facebook.com/plugins/like.php?href={% if object.get_absolute_url %}http%3A%2F%2F{{ domain }}{{ object.get_absolute_url }}{% else %}{{ object.get_share_url }}{% endif %}&amp;send=false&amp;layout=button_count&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=arial&amp;height=21&amp;appId=360681610629614" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:75px; height:21px;" allowTransparency="true"></iframe>
                {% endif %}
                </td>
            </tr>
            {# Twitter #}
            <tr>
                {# Tweet #}
                <td>
                    <a href="https://twitter.com/share" class="twitter-share-button" data-via="{{ object.twitter_account }}" data-lang="en" data-url="{% if object.get_absolute_url %}http://{{ domain }}{{ object.get_absolute_url }}{% else %}{{ object.get_share_url }}{% endif %}" data-count="none">Tweet</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                </td>
                {# Follow #}
                {% if object.twitter_account %}
                <td>
                    <a href="https://twitter.com/{{ object.twitter_account }}" class="twitter-follow-button" data-show-count="false" data-lang="en" data-width="60px">Follow</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                </td>
                {% endif %}
            </tr>
            {# Google #}
            <tr>
                {# Share #}
                <td>
                    <script src="https://apis.google.com/js/plusone.js"></script>
                    <div class="g-plus" data-action="share" data-href="{% if object.get_absolute_url %}http://{{ domain }}{{ object.get_absolute_url }}{% else %}{{ object.get_share_url }}{% endif %}" data-annotation="none"></div>
                </td>
                {# +1 #}
                <td>
                    <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
                {% if object.google_account %}
                    <div class="g-plusone" data-size="medium" data-annotation="none" data-href="{{ object.google_account }}"></div>
                {% else %}
                    <div class="g-plusone" data-size="medium" data-annotation="none" data-href="{% if object.get_absolute_url %}http://{{ domain }}{{ object.get_absolute_url }}{% else %}{{ object.get_share_url }}{% endif %}"></div>
                {% endif %}
                </td>
            </tr>
            {# e-mail #}
            <tr>
                <td></td>
                <td>
                    <span class="button mail">Enviar</span>
                </td>
            </tr>
        </tbody>
    </table>

    <div class="mail-form">
        <div class="close_popin">Cerrar X</div>
        <div class="clear"></div>
        <iframe id="mail-iframe" src="{% url send_share %}" width="260px" height="215px"></iframe>
    </div>
</div>

share/templates/simple_share_button.html
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}common/js/jquery.jqpopin/jquery.jqpopin.css" />
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}share/css/share.css" />

<script type="text/javascript" src="{{ STATIC_URL }}common/js/jquery.jqpopin/jquey.jqpopin.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}share/js/share.js"></script>

<script type="text/javascript">
    var url = "http://{{ domain }}{{ object.get_absolute_url }}";
</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=360681610629614";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="share">
    <span class="button">Share</span>
    <table>
        <tbody>
        {# Facebook #}
        <tr>
            {# Share #}
            <td>
                <a class="fb_share_button" href="http://www.facebook.com/sharer.php?u={% if object.get_absolute_url %}http%3A%2F%2F{{ domain }}{{ object.get_absolute_url }}{% else %}{{ object.get_share_url }}{% endif %}&amp;t={{ object }}" target="_blank">Share</a>
            </td>
            {# Like #}
            <td>
                <iframe src="//www.facebook.com/plugins/like.php?href={% if object.get_absolute_url %}http%3A%2F%2F{{ domain }}{{ object.get_absolute_url }}{% else %}{{ object.get_share_url }}{% endif %}&amp;send=false&amp;layout=button_count&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=arial&amp;height=21&amp;appId=360681610629614" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:75px; height:21px;" allowTransparency="true"></iframe>
            </td>
        </tr>
        {# Google #}
        <tr>
            {# Share #}
            <td>
                <script src="https://apis.google.com/js/plusone.js"></script>
                <div class="g-plus" data-action="share" data-href="{% if object.get_absolute_url %}http://{{ domain }}{{ object.get_absolute_url }}{% else %}{{ object.get_share_url }}{% endif %}" data-annotation="none"></div>
            </td>
            {# +1 #}
            <td>
                <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
                {% if object.google_account %}
                    <div class="g-plusone" data-size="medium" data-annotation="none" data-href="{{ object.google_account }}"></div>
                {% else %}
                    <div class="g-plusone" data-size="medium" data-annotation="none" data-href="{% if object.get_absolute_url %}http://{{ domain }}{{ object.get_absolute_url }}{% else %}{{ object.get_share_url }}{% endif %}"></div>
                {% endif %}
            </td>
        </tr>
        <tr>
            {# Twitter: Tweet #}
            <td>
                <a href="https://twitter.com/share" class="twitter-share-button" data-via="{{ object.twitter_account }}" data-lang="en" data-url="{% if object.get_absolute_url %}http://{{ domain }}{{ object.get_absolute_url }}{% else %}{{ object.get_share_url }}{% endif %}" data-count="none">Tweet</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </td>
            {# e-mail #}
            <td>
                <span class="button mail">Enviar</span>
            </td>
        </tr>
        </tbody>
    </table>

    <div class="mail-form">
        <div class="close_popin">Cerrar X</div>
        <div class="clear"></div>
        <iframe id="mail-iframe" src="{% url send_share %}" width="260px" height="215px"></iframe>
    </div>
</div>